---
- name: Install Kibana
  yum:
    name: kibana
    state: present
  tags: sof-elk_kibana

- name: Configure Kibana
  copy:
    src: 'kibana.yml'
    dest: '/etc/kibana/kibana.yml'
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
  tags: sof-elk_kibana

- name: Open firewall ports
  firewalld:
    port: 5601/tcp
    permanent: yes
    state: enabled
  notify: restart firewalld
  tags: sof-elk_kibana

- name: Create simple self-signed certificate
  community.crypto.x509_certificate:
    path: /usr/local/sof-elk/kibana/config/certs/kibana.crt
    privatekey_path: /usr/local/sof-elk/kibana/config/certs/kibana.key
    provider: selfsigned

- name: Enable and start Kibana service
  systemd:
    name: kibana
    enabled: yes
    state: started
  tags: sof-elk_kibana
